version: '3'
services:
  workspace:
    hostname: 'python-workspace'
    build: .
    restart: always
    working_dir: '/home/vscode/workspace'
    tty: true
    volumes:
      - type: bind
        source: '..'
        target: '/home/vscode/workspace'